excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://glennacatipon.github.io
title: The Library Hub
email: glennacatipon@gmail.com
author: glennacatipon
description: Book Promotion
paginate: 3
google_analytics: 